### ISSUE TITLE
Flatpak app hangs on "Calculating" with a FileNotFoundError

### ISSUE THREAD

**Issue by cameronbosch** [giantpinkrobots/flatsweep#1]
Hello, I was trying to use this app from Flathub, and when I tried to run it (from `flatpak run io.github.giantpinkrobots.flatsweep`), the program says "calculating", however, it never stops, and it appears to have a FileNotFoundError (with the log shown below even after quitting the app and trying again):

`Exception in thread Thread-1 (initiate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/flatsweep/flatsweep/main.py", line 181, in initiate
    flatpakListAll = listdir("/var/lib/flatpak/app") + listdir(".local/share/flatpak/app")
FileNotFoundError: [Errno 2] No such file or directory: '.local/share/flatpak/app'`

**Comment by giantpinkrobots** [comment]
Seems like I forgot to check if the folders exist before trying to get a file listing out of them. My bad. I will release the new version which should fix this right away. Please reopen this issue if the problem doesn't go away after the update. For now I am closing it.

Thanks for bringing it to my attention.

**Comment by oguzkarayemis** [comment]
Same behaviour, but different directory:
```
flatpak run io.github.giantpinkrobots.flatsweep
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
Exception in thread Thread-1 (initiate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/flatsweep/flatsweep/main.py", line 181, in initiate
    flatpakListAll = listdir("/var/lib/flatpak/app") + listdir(".local/share/flatpak/app")
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/flatpak/app'
```

**Comment by giantpinkrobots** [comment]
> Same behaviour, but different directory:
> 
> ```
> flatpak run io.github.giantpinkrobots.flatsweep
> F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
> Exception in thread Thread-1 (initiate):
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/app/share/flatsweep/flatsweep/main.py", line 181, in initiate
>     flatpakListAll = listdir("/var/lib/flatpak/app") + listdir(".local/share/flatpak/app")
> FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/flatpak/app'
> ```

Are you sure you are running the latest version? Pretty sure I have removed that line of code and replaced it with something else.

**Comment by oguzkarayemis** [comment]
> Are you sure you are running the latest version? Pretty sure I have removed that line of code and replaced it with something else.

Now I updated and issue has gone. Thank you for your effort!
