### ISSUE TITLE
Per-flatpak details/cleanup

### ISSUE THREAD

**Issue by pklampros** [giantpinkrobots/flatsweep#11]
Great little utility, thank you! I'd like a little more granularity so that I don't erase everything at once. Would it be possible to add the size of each folder, allow them to be cleaned individually and have a link to browse each folder?

**Comment by bellegarde-c** [comment]
Really needed because I have many my dev app data coming from Builder :)

**Comment by giantpinkrobots** [comment]
![screenshotFlatsweepNewPerFolderSelectio](https://github.com/giantpinkrobots/flatsweep/assets/93845996/85cc5af0-7c33-44ed-a226-ce5e000eb6d0)
Hello, thanks for the suggestion. How does this look? When you click on the items it launches the containing folders.

**Comment by bellegarde-c** [comment]
Look good.  I think you should move the scrolled window in the list box (IMO)

**Comment by pklampros** [comment]
Looks great! Thank you for being very responsive!

Would it be possible to also see the size of each directory so that we can identify the worst offenders?

**Comment by giantpinkrobots** [comment]
> Looks great! Thank you for being very responsive!
> 
> Would it be possible to also see the size of each directory so that we can identify the worst offenders?

Oh, that's a good opportunity to utilize the subtitle in Adw.ActionRow.

**Comment by giantpinkrobots** [comment]
> Look good. I think you should move the scrolled window in the list box (IMO)

I initially thought of doing that as that would look more elegant, but then I thought the window is already small enough, so in case if the list of leftover data is very long, the entire window scrolling down is the better solution.

**Comment by giantpinkrobots** [comment]
This feature has been released with the v2023.8.21 version. Therefore I am closing the issue. Thanks for the suggestions.
