### ISSUE TITLE
Flatpak Network Authorization

### ISSUE THREAD

**Issue by Froggy232** [giantpinkrobots/flatsweep#2]
Hi,
I'm very interested in your software, thanks you for your work!
I have a question, why does the app require the share=network authorization on flatpak?
In my understanding, this authorization shouldn't be necessary, but maybe I'm wrong.
Thanks you!

**Comment by giantpinkrobots** [comment]
You are right, I think it was just GNOME Builder's defaults that I appear to have left as is. The app doesn't use any network features and thus shouldn't need that permission. I am leaving this open for now, and will close it when I remove that permission with the next version that I release. Thanks for bringing this to my attention.

**Comment by Froggy232** [comment]
Nice, thanks you!

**Comment by giantpinkrobots** [comment]
Removed the network permission with the new version, closing this.

**Comment by giantpinkrobots** [comment]
> > Removed the network permission with the new version, closing this.
> 
> Thanks but Flatseal still showed network toggle on - this was my first install of Flatsweep.

Looks like I did remove it from the main json file but not on Flathub. I just released a hotfix for this, this time it should definitely be removed. Whoops.
