### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by lightonflux** [giantpinkrobots/flatsweep#24]
The big clean up or delete button should be red, if i understand the HIG correctly: 

https://developer.gnome.org/hig/patterns/controls/buttons.html#button-styles

![grafik](https://github.com/giantpinkrobots/flatsweep/assets/1377943/7797f8a4-4863-498c-a4ae-86a1675ea4b8)

**Comment by giantpinkrobots** [comment]
You're right. I have changed its color. Will be released with the next version.
![screenshot](https://github.com/giantpinkrobots/flatsweep/assets/93845996/57f53e7a-4bf7-45ca-97e9-9900eeae3542)
