### ISSUE TITLE
Padding needs to be tweaked

### ISSUE THREAD

**Issue by lightonflux** [giantpinkrobots/flatsweep#26]
![grafik](https://github.com/giantpinkrobots/flatsweep/assets/1377943/f4200038-109c-4372-a741-7c496d7cebbc)

German has long strings that reach the sides of the window.  It would look better if there was some padding to the sides. IMHO it would look best if the string was in line with the sides of the list.

**Comment by giantpinkrobots** [comment]
Will be fixed in the next version.
![screenshot](https://github.com/giantpinkrobots/flatsweep/assets/93845996/1de72385-b1d5-4b0a-85a4-9bbbd928fb4b)
