### ISSUE TITLE
Unable to clean

### ISSUE THREAD

**Issue by julien9808** [giantpinkrobots/flatsweep#30]
Hello,
the application is unable to clean the folder (658 Mb of residual data) :
com.github.micahflee.torbrowser-launcher

Message : "some files could not be deleted".

**Comment by giantpinkrobots** [comment]
That message is shown when an app's files can't be deleted for whatever reason. When you reopened the app, did it show that app's data again? If so, did trying to remove it show the same error again?

**Comment by julien9808** [comment]
The problem was solved by removing and reinstalling Tor. Flatseal was then able to clean up the remaining files.

**Comment by giantpinkrobots** [comment]
That's strange, but I'm glad it's solved. If it happens again at some point please reopen this issue.
